name: 'Match Prefix'
description: 'Action to match a prefix of an Issue Comment'
inputs:
  prefix:
    description: 'A string to match against containing no whitespace (ex. `/deploy`)'
    required: true
outputs:
  result:
    description: 'Boolean indicating if there was a match'
  actions_url:
    description: 'Actions URL for the calling repository'
  issue_number:
    description: 'Issue number of the calling comment'
  issue_actor:
    description: 'GitHub handle of the calling actor'
runs:
  using: docker
  image: Dockerfile
